# Generated by Django 4.0.2 on 2022-02-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='name',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
