# Generated by Django 3.0.3 on 2022-01-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Digikull_com', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlstable',
            name='uuid',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
