# Generated by Django 3.0.3 on 2022-01-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Digikull_com', '0002_urlstable_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlstable',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
